version: '3.5'

services:
  client:
    build:
      dockerfile: ./Dockerfile.client
    ports:
      - "5173:5173"

  server:
    build:
      dockerfile: ./Dockerfile.server
    restart: always
    ports:
      - "3000:3000"
